name: Configuration Split Ignore
type: module
description: Ignores certain configuration owned by modules enabled in configuretion splits during export and import
core: 8.x
package: Config
dependencies:
  - drupal:config_ignore
  - drupal:config_split
