config_split.config_split.*.third_party.config_split_ignore:
  type: mapping
  label: 'Configuration Split Ignore settings'
  mapping:
    entities:
      type: sequence
      label: 'List of ignored configurations'
      sequence:
        type: string
